# Zsh History

export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000

# Enable zsh highlighting and suggestions
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# Enable zsh completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' menu yes select
autoload -Uz compinit && compinit

# Starship Prompt
eval "$(starship init zsh)"

#  
# Aliases
# 


# Navigation
alias ls='exa --icons -l'
alias la='exa --icons -la'
alias ..='cd ..'
alias ...='cd ../..'

# Copy from usb drive
alias cp_usb_cours='cd /run/media/bastien/SanDisk/INFO; cp -r  * ~/Documents/info-cours; cd ~/Documents/info-cours'

alias cp_cours_usb='cd ~/Documents/info-cours; cp -r  * /run/media/bastien/SanDisk/INFO; cd /run/media/bastien/SanDisk/INFO'



# Python Virtual Env.
function venv () 
{
	python -m venv ~/venv/$1 ; source ~/venv/$1/bin/activate
}

# opam configuration
[[ ! -r /home/bastien/.opam/opam-init/init.zsh ]] || source /home/bastien/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
